// Hero roster. To add a hero: drop a 240x390 portrait into Assets/HeroPick/
// and add one line here: h('Display Name', 'filename-without-.png', 'Role/Role').
(function (global) {
    'use strict';

    const list = [];
    function h(name, file, roles) {
        list.push({ id: file, name: name, roles: roles.split('/'), img: 'Assets/HeroPick/' + file + '.png' });
    }

    h('Aamon', 'aamon', 'Assassin');
    h('Akai', 'akai', 'Tank');
    h('Aldous', 'aldous', 'Fighter');
    h('Alice', 'alice', 'Mage/Tank');
    h('Alpha', 'alpha', 'Fighter');
    h('Alucard', 'alucard', 'Fighter/Assassin');
    h('Angela', 'angela', 'Support');
    h('Argus', 'argus', 'Fighter');
    h('Arlott', 'arlot', 'Fighter/Assassin');
    h('Atlas', 'atlas', 'Tank');
    h('Aulus', 'aulus', 'Fighter');
    h('Aurora', 'aurora', 'Mage');
    h('Badang', 'badang', 'Fighter');
    h('Balmond', 'balmond', 'Fighter');
    h('Bane', 'bane', 'Fighter/Mage');
    h('Barats', 'barats', 'Tank/Fighter');
    h('Baxia', 'baxia', 'Tank');
    h('Beatrix', 'beatrix', 'Marksman');
    h('Belerick', 'beleric', 'Tank');
    h('Benedetta', 'benedetta', 'Assassin/Fighter');
    h('Brody', 'brody', 'Marksman');
    h('Bruno', 'bruno', 'Marksman');
    h('Carmilla', 'carmila', 'Support/Tank');
    h('Cecilion', 'cecilion', 'Mage');
    h("Chang'e", 'chang_e', 'Mage');
    h('Chip', 'chip', 'Support/Tank');
    h('Chou', 'chou', 'Fighter');
    h('Cici', 'cici', 'Fighter');
    h('Claude', 'claude', 'Marksman');
    h('Clint', 'clint', 'Marksman');
    h('Cyclops', 'cyclops', 'Mage');
    h('Diggie', 'diggie', 'Support');
    h('Dyrroth', 'dyroth', 'Fighter');
    h('Edith', 'edith', 'Tank/Marksman');
    h('Esmeralda', 'esmeralda', 'Mage/Tank');
    h('Estes', 'estes', 'Support');
    h('Eudora', 'eudora', 'Mage');
    h('Fanny', 'fanny', 'Assassin');
    h('Faramis', 'faramis', 'Support/Mage');
    h('Floryn', 'floryn', 'Support');
    h('Franco', 'franco', 'Tank');
    h('Fredrinn', 'fredrin', 'Fighter/Tank');
    h('Freya', 'freya', 'Fighter');
    h('Gatotkaca', 'gatotkaca', 'Tank/Fighter');
    h('Gloo', 'gloo', 'Tank');
    h('Gord', 'gord', 'Mage');
    h('Granger', 'granger', 'Marksman');
    h('Grock', 'grock', 'Tank/Fighter');
    h('Guinevere', 'guinevere', 'Fighter');
    h('Gusion', 'gusion', 'Assassin');
    h('Hanabi', 'hanabi', 'Marksman');
    h('Hanzo', 'hanzo', 'Assassin');
    h('Harith', 'harith', 'Mage');
    h('Harley', 'harley', 'Assassin/Mage');
    h('Hayabusa', 'hayabusa', 'Assassin');
    h('Helcurt', 'helcurt', 'Assassin');
    h('Hilda', 'hilda', 'Fighter/Tank');
    h('Hirara', 'hirara', 'Assassin');
    h('Hylos', 'hylos', 'Tank');
    h('Irithel', 'irithel', 'Marksman');
    h('Ixia', 'ixia', 'Marksman');
    h('Jawhead', 'jawhead', 'Fighter');
    h('Johnson', 'johnson', 'Tank/Support');
    h('Joy', 'joy', 'Assassin');
    h('Julian', 'julian', 'Fighter/Mage');
    h('Kadita', 'kadita', 'Mage/Assassin');
    h('Kagura', 'kagura', 'Mage');
    h('Kaja', 'kaja', 'Support/Fighter');
    h('Kalea', 'kalea', 'Support/Fighter');
    h('Karina', 'karina', 'Assassin');
    h('Karrie', 'karrie', 'Marksman');
    h('Khaleed', 'khaleed', 'Fighter');
    h('Khufra', 'khufra', 'Tank');
    h('Kimmy', 'kimmy', 'Marksman/Mage');
    h('Lancelot', 'lancelot', 'Assassin');
    h('Lapu-Lapu', 'lapulapu', 'Fighter');
    h('Layla', 'layla', 'Marksman');
    h('Leomord', 'leomord', 'Fighter');
    h('Lesley', 'lesley', 'Marksman/Assassin');
    h('Ling', 'ling', 'Assassin');
    h('Lolita', 'lolita', 'Support/Tank');
    h('Lukas', 'lukas', 'Fighter');
    h('Lunox', 'lunox', 'Mage');
    h('Luo Yi', 'luoyi', 'Mage');
    h('Lylia', 'lylia', 'Mage');
    h('Marcel', 'marcel', 'Support/Tank');
    h('Martis', 'martis', 'Fighter');
    h('Masha', 'masha', 'Fighter/Tank');
    h('Mathilda', 'mathilda', 'Support/Assassin');
    h('Melissa', 'melissa', 'Marksman');
    h('Minotaur', 'minotour', 'Tank/Support');
    h('Minsitthar', 'minsitthar', 'Fighter');
    h('Miya', 'miya', 'Marksman');
    h('Moskov', 'moskov', 'Marksman');
    h('Nana', 'nana', 'Mage');
    h('Natalia', 'natalia', 'Assassin');
    h('Natan', 'nathan', 'Marksman');
    h('Nolan', 'nolan', 'Assassin');
    h('Novaria', 'novaria', 'Mage');
    h('Obsidia', 'obsidia', 'Marksman');
    h('Odette', 'odette', 'Mage');
    h('Paquito', 'paquito', 'Fighter/Assassin');
    h('Pharsa', 'parsha', 'Mage');
    h('Phoveus', 'phoveus', 'Fighter');
    h('Popol and Kupa', 'popolandkupa', 'Marksman');
    h('Rafaela', 'rafaela', 'Support');
    h('Roger', 'roger', 'Fighter/Marksman');
    h('Ruby', 'ruby', 'Fighter');
    h('Saber', 'saber', 'Assassin');
    h('Selena', 'selena', 'Assassin/Mage');
    h('Silvanna', 'silvanna', 'Fighter');
    h('Sora', 'sora', 'Fighter/Assassin');
    h('Sun', 'sun', 'Fighter');
    h('Suyou', 'suyou', 'Assassin/Fighter');
    h('Terizla', 'terizla', 'Fighter');
    h('Thamuz', 'thamuz', 'Fighter');
    h('Tigreal', 'tigreal', 'Tank');
    h('Uranus', 'uranus', 'Tank');
    h('Vale', 'vale', 'Mage');
    h('Valentina', 'valentina', 'Mage');
    h('Valir', 'valir', 'Mage');
    h('Vexana', 'vexana', 'Mage');
    h('Wanwan', 'wanwan', 'Marksman');
    h('Xavier', 'xavier', 'Mage');
    h('X.Borg', 'xborg', 'Fighter');
    h('Yi Sun-shin', 'yisunshin', 'Assassin/Marksman');
    h('Yin', 'yin', 'Fighter/Assassin');
    h('Yu Zhong', 'yuzhong', 'Fighter');
    h('Yve', 'yve', 'Mage');
    h('Zetian', 'zetian', 'Mage');
    h('Zhask', 'zhask', 'Mage');
    h('Zhuxin', 'zhuxin', 'Mage');
    h('Zilong', 'zilong', 'Fighter/Assassin');

    const byId = {};
    list.forEach(function (hero) { byId[hero.id] = hero; });

    global.Heroes = {
        list: list,
        roles: ['Tank', 'Fighter', 'Assassin', 'Mage', 'Marksman', 'Support'],
        get: function (id) { return id ? byId[id] || null : null; }
    };
})(window);
